version: "3"

services:
  app:
    build:
      context: .
    command: node index.js
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app
    networks:
      - challenge
    tty: true
    depends_on:
      - db

  proxy:
    image: nginx:1.23.3-alpine
    container_name: proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - challenge
    depends_on:
      - app

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=dbase
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - challenge

networks:
  challenge:
    driver: bridge
